config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :categories
  resources :products
  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "products#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_rich_text :description
  has_many_attached :image
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_rich_text :description
  has_many_attached :images
  has_and_belongs_to_many :sizes
  belongs_to :category, optional: true
end

app/models/size.rb
class Size < ApplicationRecord
    has_and_belongs_to_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :check_admin_priv
def def show
    
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def check_admin_priv
    if !current_admin
    redirect_to root_path 
    end 
  end 
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_admin_priv, except: ["index", "show"]
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, image: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_admin_priv, except: ["index", "show"]
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.size_ids = @product.size_ids.reject(&:blank?)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    new_product_params = product_params.to_unsafe_h
    new_product_params.delete("images") if new_product_params["images"].all?(&:blank?)
    respond_to do |format|
      if @product.update(new_product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :size_ids, images: [])
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/show.html.erb
<div>                                           
   <h1 class="text-6xl">Welcome to Admin Mode!</h1>
     <div class="flex gap-4 mt-6"> 
     <%= link_to "New Product", new_product_path, class: "p-2 rounded-lg bg-blue-500 text-blue-100" %>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category, class: "w-full" do %>
<div id="<%= dom_id category %>" class="relative flex items-center justify-center">
 <%= image_tag category.image.first, class: "w-full h-80 object-cover rounded-lg  brightness-75 hover:brightness-50 transition-all duration-250" if  category.image.attached? %>
  <p class="text-lg text-blue-800 font-bold absolute bg-green-500 text-center rounded-lg py-2 px-3 "><%= category.name %></p>
</div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, multiple: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Categories" %>

  <h1 class="font-bold text-8xl text-center font-sweety text-black">All Categories</h1>

  <div id="categories" class="min-w-full grid md:grid-cols-4 gap-8">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full bg-gray-200/75 p-2 rounded-lg">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="w-full flex flex-col">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="relative flex items-center justify-center">
    <% if @category.image.attached? %>
      <%= image_tag @category.image.first, class: "w-full h-80 object-cover rounded-lg brightness-75 hover:brightness-50 transition-all duration-250" %>
    <% end %>
    <h1 class="font-bold text-8xl text-center font-sweety text-white absolute"><%= @category.name %></h1>
  </div>

  <div class="max-w-xl text-black text-3xl font-bold mx-auto mt-4">
    <%= @category.description %>
  </div>

  <div id="products" class="min-w-full grid grid-cols-4 gap-8">
    <% @category.products.each do |product| %>
      <%= render "products/product", product: product %>
    <% end %>
  </div> 

  <% if current_admin %>
    <div class="w-full flex justify-center items-center mt-16 gap-4"> 
      <%= link_to "Edit this category", edit_category_path(@category), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Back to categories", categories_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this category", @category, method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="h-16  w-full fixed top-0 left-0 right-0 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 z-50 shadow-lg rounded-lg">
  <div class="max-w-7xl h-full mx-auto flex items-center justify-between px-6">
    <%= link_to root_path, class: "flex items-center gap-2 justify-between" do %>
      <%= image_tag("shop.png", class: "w-10 h-10 object-cover ") %>
      <span class="text-2xl font-bold text-white  px-4 tracking-wide">Ecommerce Violet Store</span>
    <% end %>

    <div class="flex items-center gap-4 px-4">
      <% if current_user %>
        <%= link_to "Sign Out", destroy_user_session_path, 
                    data: { turbo_method: :delete }, 
                    class: "px-4 py-2 text-white font-semibold bg-red-600 hover:bg-gray-700 rounded-lg border border-gray-200 shadow transition duration-300" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, 
                    class: "px-4 py-2 text-indigo-700 font-semibold bg-white hover:brightness-75 rounded-lg shadow border border-indigo-700 transition duration-300" %>
        <%= link_to "Sign Up", new_user_registration_path, 
                    class: "px-4 py-2 text-white font-semibold hover:bg-black hover:brightness-75  rounded-lg shadow transition duration-300 border border-gray-200" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Store Violeth" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gradient-to-r from-indigo-500 to-pink-500 text-black bg-indigo-500">
    <%= render "layouts/navbar" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: @product, class: "contents", local: true) do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Campo para el nombre del producto -->
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <!-- Campo para la descripción -->
  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <!-- Campo para el precio -->
  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <!-- Campo para seleccionar la categoría -->
  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select Category" }, class: "form-control" %>
  </div>

  <!-- Campo para seleccionar múltiples tallas (Sizes) -->
  <div class="my-5">
    <%= form.label :size_ids, "Available Sizes" %>
    <%= form.collection_check_boxes :size_ids, Size.all, :id, :name do |b| %>
      <div class="inline-block mr-4">
        <%= b.check_box %>
        <%= b.label(class: "ml-2") %>
      </div>
    <% end %>
  </div>

  <!-- Campo para seleccionar imágenes -->
  <div class="my-5">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full bg-gray-100" %>
  </div>

  <!-- Botón para enviar el formulario -->
  <div class="inline">
    <%= form.submit "Create Product", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>

<% end %>

app/views/products/_product.html.erb
<%= link_to product, class: "w-full" do %>
<div id="<%= dom_id product %>">
 <%= image_tag product.images.first, class: "w-full h-80 object-cover rounded-lg hover:brightness-75 transition-all duration-250" if  product.images.any? %>
  <p class="font-bold text-lg text-center text-blue-800"><%= product.name %></p>
  <p class="font-bold text-lg text-center text-blue-800"><%= number_to_currency product.price %></p>
</div>
<% end %>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to Admin", admin_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "The Best Products" %>

  <h1 class="font-bold text-8xl text-center font-sweety text-black">VIOLETH STORE</h1>

  <br>
  <br>

  <div id="products" class="min-w-full grid md:grid-cols-4 gap-8">
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </div>

  <br>

  <div class="mt-4 w-full font-bold">  
    <%= link_to "Shop by category", categories_path, class: "text-xl font-bold text-black bg-blue-200 rounded-lg py-3 px-5" %>
  </div>

  <div class="space-y-8 mt-8 text-center justify-center">
    <h3 class="text-3xl font-bold text-white  ">
      Contact:
    </h3>
    <ul class="mt-4 space-y-4">
      <li>
        <p class="text-base leading-6 text-white">
          Address: <%= link_to "Calle 53A # 92A-48, Medellin, Colombia" %>
        </p>
      </li>
      <li>
        <p class="text-base leading-6 text-white">
          Email: <%= link_to "noslenque931gmail.com" %>
        </p>
      </li>
      <li>
        <p class="text-base leading-6 text-white">
          Phone: <%= link_to "+573022069265"%>
        </p>
      </li>
    </ul>
  </div>
  <div class="border-t border-gray-700 mt-8 text-center justify-center">
    <div class="max-w-6xl mx-auto px-4 py-6 md:flex md:items-center md:justify-between">
      <p class="mt-6 text-base leading-6 text-gray-400 md:mt-0 md:order-1">
        &copy; <%= Time.now.year %> Ecomm, Inc. All rights reserved.
      </p>
    </div>
</div>


</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full bg-gray-200/75 p-2 rounded-lg">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to Admin", admin_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="w-full">
  
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="max-w-7xl w-full mx-auto px-10 font-bold mb-2">
    <%= link_to "Products", products_path, class: "text-xl font-bold text-black hover:underline hover:text-blue-500 bg-blue-50 rounded-lg py-3 px-5" %>
    <%= link_to "> #{ @product.category.name}", @product.category, class: "text-xl font-bold text-black" if @product.category %>
    <%= link_to "> #{ @product.name}", @product, class: "text-xl font-bold text-black" %> 
  </div>
  <br>
  <div class="grid md:grid-cols-2">
   <div class="max-w-md w-full mx-auto">
     <% if @product.images.any? %>
     <%= image_tag @product.images.first, class: "w-full h-96 object-cover"%>
     <div class="grid grid-cols-3 gap-4 mt-4">
       <% @product.images[1..-1].each do |image| %>
         <%= image_tag image, class: "w-full h-32 object-cover" %>
       <% end %>
     </div>
     <% end %>
   </div>
   <div class="max-w-xl">
     <h1 class="text-5xl font-sweety text-blue-800 "><%= @product.name %></h1>
     <div class="max-w-sm text-black/75 font-bold">
      <%= @product.description %>
      <br>
     </div>
     <span class="bg-green-500 rounded-lg text-black py-2 px-3"><%= number_to_currency @product.price %></span>
   </div>
  </div>

  <p><strong>Available Sizes:</strong></p>
<ul>
  <% @product.sizes.each do |size| %>
    <li><%= size.name %></li>
  <% end %>
</ul>


 <div class="w-full flex justify-center items-center mt-16 gap-4">
  <%= link_to "Edit this product", edit_product_path(@product), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

  <div class="inline-block ml-2">
  <%= button_to "Destroy this product", @product, method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
 
</div>
</div>